import "server-only";
import type { DataSourceConnector, NormalisedLead, RawRecord } from "./types";

// Demo build: every connector returns a fresh batch of realistic sample
// records instead of calling Companies House, PlanIt or a Socrata portal.
// Records flow through the same commit pipeline (validation, suppression
// screening, de-duplication, insert) as real ones would.

const FIRST = ["Adam", "Beth", "Callum", "Dina", "Edward", "Farah", "Gavin", "Holly", "Isaac", "Jade", "Kieran", "Leah", "Mason", "Nadia", "Owen", "Priya"];
const LAST = ["Archer", "Bishop", "Chapman", "Dawson", "Ellis", "Fletcher", "Gibson", "Hayes", "Irving", "Jennings", "Knight", "Lawson"];
const COMPANY = ["Ridgeway", "Stonebridge", "Oakfield", "Brightwater", "Castleford", "Fairview", "Kestrel", "Longmead", "Marlow", "Westbrook"];
const SUFFIX = ["Builders Ltd", "Developments", "Roofing Co", "Homes Ltd", "Construction", "Property Group"];
const UK_TOWNS = ["Leeds", "Bristol", "Nottingham", "Leicester", "Coventry", "Derby", "Bath", "Exeter"];
const US_TOWNS = ["Austin", "Round Rock", "Pflugerville", "Cedar Park", "Georgetown"];

function pick<T>(arr: T[]) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function makeDemoConnector(
  key: string,
  market: "UK" | "US",
  lawfulBasis: DataSourceConnector["lawfulBasis"],
  sourceUrl: string,
): DataSourceConnector {
  return {
    key,
    market,
    lawfulBasis,
    async fetch(params) {
      const count = Math.min(Math.max(Number(params.itemsPerPage ?? params.limit ?? 12) || 12, 1), 50);
      const retrievedAt = new Date().toISOString();
      return Array.from({ length: count }, (_, i) => {
        const us = market === "US";
        const first = pick(FIRST);
        const last = pick(LAST);
        const ref = `${key.slice(0, 3).toUpperCase()}-${Date.now().toString(36).toUpperCase()}-${i}`;
        return {
          data: {
            ref,
            first,
            last,
            company: `${pick(COMPANY)} ${pick(SUFFIX)}`,
            // One in eight records has no phone number, like real registers.
            phone: i % 8 === 7 ? null : us ? `+1512${Math.floor(2_000_000 + Math.random() * 7_999_999)}` : `+447${Math.floor(100_000_000 + Math.random() * 899_999_999)}`,
            town: us ? pick(US_TOWNS) : pick(UK_TOWNS),
            query: params.query ?? null,
          },
          sourceUrl: `${sourceUrl}#${ref}`,
          retrievedAt,
        } satisfies RawRecord;
      });
    },
    normalise(raw: RawRecord): NormalisedLead | null {
      const d = raw.data as Record<string, string | null>;
      return {
        externalRef: d.ref ?? undefined,
        firstName: d.first ?? undefined,
        lastName: d.last ?? undefined,
        companyName: d.company ?? undefined,
        jobTitle: "Director",
        phoneRaw: d.phone ?? undefined,
        countryHint: market === "US" ? "US" : "GB",
        city: d.town ?? undefined,
        custom: { source: key, source_notes: "Sample record generated by the demo connector" },
      };
    },
  };
}
